### PR TITLE
Improve gap rendering

### PR DESCRIPTION
**Pull request by holfordm**
attempts to address issue #40

### CODE REVIEW

**Comment by andrew-morrison** [comment]
What should be displayed when the gap has no `@unit`, or a `@reason` which is something other than "editorial"?

**Comment by holfordm** [comment]
ellipsis with no spaces either side. 
Editorial gaps could be further distinguished by appearing as " [...] " i.e. space either side of ellipsis in square brackets.

**Comment by andrew-morrison** [comment]
In that case the `[not(@unit) and not(@reason)]` should be removed. In XSLT, templates with more specific matches take precedence over more generic ones. So you can (and probably should) have one template that just matches any `gap` element, doing the default, then override that with templates for specific cases (like the editorial ones.)

If you want square brackets around the ellipsis for editorial gaps, then add those into the XSLT.

**Comment by holfordm** [comment]
On closer investigation I see the existing templates are working in some contexts (e.g. https://medieval.bodleian.ox.ac.uk/catalog/manuscript_107) and the problem is in the use of `char` / `chars`, which I'll fix.

**Comment by andrew-morrison** [comment]
Probably best to standardize on `char` as that is what the TEI schema suggests, so is what Oxygen offers in an autocomplete drop-down.

**Comment by andrew-morrison** [comment]
I have re-indexed Medieval QA, using the latest TEI from the master branch of medieval-mss, and XSLT from this branch, if you want to see the effect of your changes to `gap`.

I'll merge then re-index production at the end of today, unless I hear otherwise.

**Pull request merged**
