### PR TITLE
Updates april 2020

### PR DESCRIPTION
**Pull request by holfordm**
updates and improvements

### CODE REVIEW

**Comment by andrew-morrison** [comment]
The TEI P5 core has moved on to version 4.0.0, so Relax NG and other schemas generated will include the changes listed here (the ones that apply to the modules we use):

https://tei-c.org/Vault/P5/4.0.0/doc/tei-p5-doc/readme-4.0.0.html

Is there anything in there that needs testing, or suggest further changes?

**Comment by andrew-morrison** [comment]
Also any objection to adding biblStruct as requested in #35?

**Comment by andrew-morrison** [comment]
So `execution` and `type` are brand new attributes on `handNote` elements. Should they:

 * Both be optional?
 * Both be allowed to contain any value, with the lists supplied the recommendations?
 * Both be single-value? Or allow multiple values separated by spaces?

It would also be good to have a single-sentence description of what `type` means in the context of handNote.

**Comment by holfordm** [comment]
sorry, that should have been `@script` not `@type` on handNote - now corrected.
the `execution` attribute should be optional and allow other values as well as the recommendations, but not allow multiple values.

**Comment by holfordm** [comment]
I can't see anything in TEI 4.0.0 that should worry us...

**Comment by andrew-morrison** [comment]
I've built and tested a new msdesc.rng. If you want to double check, you can copy and paste the following into the xml-model of any of your files:

https://raw.githubusercontent.com/msDesc/consolidated-tei-schema/updates-april-2020/msdesc.rng

Oxygen will then validate against it, and display suggested values from the new valLists.

Before I merge and do a release, I have one more question about the wording of the description of the new `execution` attribute. It says, "The default value is assumed to be libraria." By that do you mean in the context of the Medieval catalogue only? As in at some point you'd like medieval.bodleian.ox.ac.uk to display "Execution: libraria" when there is no execution attribute, or maybe use it in search filters? It could be made the default as defined in the schema, but then for every record which uses this schema a validating parser will return "libraria" if you ask it via XPath what the execution is.

**Pull request merged**
