### PR TITLE
Changes june 2021

### PR DESCRIPTION
**Pull request by holfordm**

### CODE REVIEW

**Comment by andrew-morrison** [comment]
Both `damage` elements and `defective` attributes are used in other catalogues. Is the notation being added by the stylesheet specific to Medieval or universal?

There is nothing wrong with the XSLT syntax.

**Comment by holfordm** [comment]
Even within medieval Western catalogues, notation for these things varies, but I think this notation is universally comprehensible. Certainly the defective ttribute is just an extension of what we already have for `incipit` and `explicit`. Do we have colleagues from Fihrist or other catalogues on this repo who might comment?

**Comment by andrew-morrison** [comment]
Looking more closely, `damage` has been used by a couple of Fihrist institutions to mark up descriptions of damage in `physDesc`. For example:
 
 * https://github.com/fihristorg/fihrist-mss/blob/master/collections/the%20university%20of%20manchester/Persian_MS_90.xml#L202
 * https://github.com/fihristorg/fihrist-mss/blob/master/collections/wadham%20college%20(university%20of%20oxford)/WadhMinasian_708.xml#L76

You could add some context, so the new template only matches `damage` when inside certain other elements, but if the above are using it wrong it might be just as well to keep it as-is, to discourage further incorrect usage.

There are very little usage of `rubric` or `finalRubric`, and none with the `defective` attribute, but here's an example in Fihrist of the `defective` attribute in both `incipit` and `explicit`:

 * https://github.com/fihristorg/fihrist-mss/blob/master/collections/oxford%20university/MS_S_Digby_Or_189.xml#L65-L69

Which is displayed like this:

 * https://www.fihrist.org.uk/catalog/manuscript_12853

Alasdair created that record after the new Fihrist web site launched, so it would've displayed that way when he did so.

**Comment by holfordm** [comment]
The current guidelines are clear that it should be used for "an area of damage to the text witness." Extending that to use the element to describe the nature of damage to an object is perhaps logical but strictly should either be noted in our ODD or submitted to TEI council. (Can we pass this on to the Fihrist mailing list?)

**Comment by andrew-morrison** [comment]
I've sent an email to the Fihrist mailing list.

I've now merged this pull request. I don't create new releases for tweaks to the XSLT.

**Pull request merged**
